# Generated by Django 4.1.2 on 2023-02-18 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matn', models.CharField(max_length=200)),
                ('ism', models.CharField(max_length=30)),
                ('sana', models.DateField(auto_now_add=True)),
                ('maqola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.maqolalar')),
            ],
        ),
    ]
